layout_spectrum: 0.2096774
typography_spectrum: 0.4874552
color:
  saturation: 0.2124955
  lightness: 0.1011984
  brandStrength: 0.9147374
  rhythmicContrast: 0.1398095
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: jgro
